[package]
name = "MacaBell"
version = "0.3.0"
description = "A soft pastel macOS menu bar reminder app"
authors = ["yixiao-lab"]
edition = "2021"

[lib]
# The `_lib` suffix may seem redundant but it is necessary to make the lib name unique
# and avoid conflicts with the binary name on some platforms.
name = "macaron_reminder_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "macos-private-api"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["clock"] }
tauri-plugin-autostart = "2"
